/* ewsExchangeServiceBindingProxy.h
   Generated by gSOAP 2.8.21 from Services.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef ewsExchangeServiceBindingProxy_H
#define ewsExchangeServiceBindingProxy_H
#include "ewsH.h"

class SOAP_CMAC ExchangeServiceBindingProxy : public soap
{ public:
	/// Endpoint URL of service 'ExchangeServiceBindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Variables globally declared in Services.h (non-static)
	/// Constructor
	ExchangeServiceBindingProxy();
	/// Construct from another engine state
	ExchangeServiceBindingProxy(const struct soap&);
	/// Constructor with endpoint URL
	ExchangeServiceBindingProxy(const char *url);
	/// Constructor with engine input+output mode control
	ExchangeServiceBindingProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	ExchangeServiceBindingProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	ExchangeServiceBindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~ExchangeServiceBindingProxy();
	/// Initializer used by constructors
	virtual	void ExchangeServiceBindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Put SOAP Header in message
	virtual	void soap_header(ews2__ExchangeImpersonationType *ews2__ExchangeImpersonation, std::string *ews2__MailboxCulture, enum ews2__AvailabilityProxyRequestType *ews2__ProxyRequestTypeHeader, _ews2__RequestServerVersion *ews2__RequestServerVersion, ews2__SerializedSecurityContextType *ews2__SerializedSecurityContext, _ews2__ServerVersionInfo *ews2__ServerVersionInfo, ews2__TimeZoneContextType *ews2__TimeZoneContext);
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'ResolveNames' (returns error code or SOAP_OK)
	virtual	int ResolveNames(ews1__ResolveNamesType *ews1__ResolveNames, struct __ews1__ResolveNamesResponse &_param_1) { return this->ResolveNames(NULL, NULL, ews1__ResolveNames, _param_1); }
	virtual	int ResolveNames(const char *endpoint, const char *soap_action, ews1__ResolveNamesType *ews1__ResolveNames, struct __ews1__ResolveNamesResponse &_param_1);

	/// Web service operation 'ExpandDL' (returns error code or SOAP_OK)
	virtual	int ExpandDL(ews1__ExpandDLType *ews1__ExpandDL, struct __ews1__ExpandDLResponse &_param_2) { return this->ExpandDL(NULL, NULL, ews1__ExpandDL, _param_2); }
	virtual	int ExpandDL(const char *endpoint, const char *soap_action, ews1__ExpandDLType *ews1__ExpandDL, struct __ews1__ExpandDLResponse &_param_2);

	/// Web service operation 'FindFolder' (returns error code or SOAP_OK)
	virtual	int FindFolder(ews1__FindFolderType *ews1__FindFolder, struct __ews1__FindFolderResponse &_param_3) { return this->FindFolder(NULL, NULL, ews1__FindFolder, _param_3); }
	virtual	int FindFolder(const char *endpoint, const char *soap_action, ews1__FindFolderType *ews1__FindFolder, struct __ews1__FindFolderResponse &_param_3);

	/// Web service operation 'FindItem' (returns error code or SOAP_OK)
	virtual	int FindItem(ews1__FindItemType *ews1__FindItem, struct __ews1__FindItemResponse &_param_4) { return this->FindItem(NULL, NULL, ews1__FindItem, _param_4); }
	virtual	int FindItem(const char *endpoint, const char *soap_action, ews1__FindItemType *ews1__FindItem, struct __ews1__FindItemResponse &_param_4);

	/// Web service operation 'GetFolder' (returns error code or SOAP_OK)
	virtual	int GetFolder(ews1__GetFolderType *ews1__GetFolder, struct __ews1__GetFolderResponse &_param_5) { return this->GetFolder(NULL, NULL, ews1__GetFolder, _param_5); }
	virtual	int GetFolder(const char *endpoint, const char *soap_action, ews1__GetFolderType *ews1__GetFolder, struct __ews1__GetFolderResponse &_param_5);

	/// Web service operation 'ConvertId' (returns error code or SOAP_OK)
	virtual	int ConvertId(ews1__ConvertIdType *ews1__ConvertId, struct __ews1__ConvertIdResponse &_param_6) { return this->ConvertId(NULL, NULL, ews1__ConvertId, _param_6); }
	virtual	int ConvertId(const char *endpoint, const char *soap_action, ews1__ConvertIdType *ews1__ConvertId, struct __ews1__ConvertIdResponse &_param_6);

	/// Web service operation 'CreateFolder' (returns error code or SOAP_OK)
	virtual	int CreateFolder(ews1__CreateFolderType *ews1__CreateFolder, struct __ews1__CreateFolderResponse &_param_7) { return this->CreateFolder(NULL, NULL, ews1__CreateFolder, _param_7); }
	virtual	int CreateFolder(const char *endpoint, const char *soap_action, ews1__CreateFolderType *ews1__CreateFolder, struct __ews1__CreateFolderResponse &_param_7);

	/// Web service operation 'DeleteFolder' (returns error code or SOAP_OK)
	virtual	int DeleteFolder(ews1__DeleteFolderType *ews1__DeleteFolder, struct __ews1__DeleteFolderResponse &_param_8) { return this->DeleteFolder(NULL, NULL, ews1__DeleteFolder, _param_8); }
	virtual	int DeleteFolder(const char *endpoint, const char *soap_action, ews1__DeleteFolderType *ews1__DeleteFolder, struct __ews1__DeleteFolderResponse &_param_8);

	/// Web service operation 'UpdateFolder' (returns error code or SOAP_OK)
	virtual	int UpdateFolder(ews1__UpdateFolderType *ews1__UpdateFolder, struct __ews1__UpdateFolderResponse &_param_9) { return this->UpdateFolder(NULL, NULL, ews1__UpdateFolder, _param_9); }
	virtual	int UpdateFolder(const char *endpoint, const char *soap_action, ews1__UpdateFolderType *ews1__UpdateFolder, struct __ews1__UpdateFolderResponse &_param_9);

	/// Web service operation 'MoveFolder' (returns error code or SOAP_OK)
	virtual	int MoveFolder(ews1__MoveFolderType *ews1__MoveFolder, struct __ews1__MoveFolderResponse &_param_10) { return this->MoveFolder(NULL, NULL, ews1__MoveFolder, _param_10); }
	virtual	int MoveFolder(const char *endpoint, const char *soap_action, ews1__MoveFolderType *ews1__MoveFolder, struct __ews1__MoveFolderResponse &_param_10);

	/// Web service operation 'CopyFolder' (returns error code or SOAP_OK)
	virtual	int CopyFolder(ews1__CopyFolderType *ews1__CopyFolder, struct __ews1__CopyFolderResponse &_param_11) { return this->CopyFolder(NULL, NULL, ews1__CopyFolder, _param_11); }
	virtual	int CopyFolder(const char *endpoint, const char *soap_action, ews1__CopyFolderType *ews1__CopyFolder, struct __ews1__CopyFolderResponse &_param_11);

	/// Web service operation 'Subscribe' (returns error code or SOAP_OK)
	virtual	int Subscribe(ews1__SubscribeType *ews1__Subscribe, struct __ews1__SubscribeResponse &_param_12) { return this->Subscribe(NULL, NULL, ews1__Subscribe, _param_12); }
	virtual	int Subscribe(const char *endpoint, const char *soap_action, ews1__SubscribeType *ews1__Subscribe, struct __ews1__SubscribeResponse &_param_12);

	/// Web service operation 'Unsubscribe' (returns error code or SOAP_OK)
	virtual	int Unsubscribe(ews1__UnsubscribeType *ews1__Unsubscribe, struct __ews1__UnsubscribeResponse &_param_13) { return this->Unsubscribe(NULL, NULL, ews1__Unsubscribe, _param_13); }
	virtual	int Unsubscribe(const char *endpoint, const char *soap_action, ews1__UnsubscribeType *ews1__Unsubscribe, struct __ews1__UnsubscribeResponse &_param_13);

	/// Web service operation 'GetEvents' (returns error code or SOAP_OK)
	virtual	int GetEvents(ews1__GetEventsType *ews1__GetEvents, struct __ews1__GetEventsResponse &_param_14) { return this->GetEvents(NULL, NULL, ews1__GetEvents, _param_14); }
	virtual	int GetEvents(const char *endpoint, const char *soap_action, ews1__GetEventsType *ews1__GetEvents, struct __ews1__GetEventsResponse &_param_14);

	/// Web service operation 'SyncFolderHierarchy' (returns error code or SOAP_OK)
	virtual	int SyncFolderHierarchy(ews1__SyncFolderHierarchyType *ews1__SyncFolderHierarchy, struct __ews1__SyncFolderHierarchyResponse &_param_15) { return this->SyncFolderHierarchy(NULL, NULL, ews1__SyncFolderHierarchy, _param_15); }
	virtual	int SyncFolderHierarchy(const char *endpoint, const char *soap_action, ews1__SyncFolderHierarchyType *ews1__SyncFolderHierarchy, struct __ews1__SyncFolderHierarchyResponse &_param_15);

	/// Web service operation 'SyncFolderItems' (returns error code or SOAP_OK)
	virtual	int SyncFolderItems(ews1__SyncFolderItemsType *ews1__SyncFolderItems, struct __ews1__SyncFolderItemsResponse &_param_16) { return this->SyncFolderItems(NULL, NULL, ews1__SyncFolderItems, _param_16); }
	virtual	int SyncFolderItems(const char *endpoint, const char *soap_action, ews1__SyncFolderItemsType *ews1__SyncFolderItems, struct __ews1__SyncFolderItemsResponse &_param_16);

	/// Web service operation 'GetItem' (returns error code or SOAP_OK)
	virtual	int GetItem(ews1__GetItemType *ews1__GetItem, struct __ews1__GetItemResponse &_param_17) { return this->GetItem(NULL, NULL, ews1__GetItem, _param_17); }
	virtual	int GetItem(const char *endpoint, const char *soap_action, ews1__GetItemType *ews1__GetItem, struct __ews1__GetItemResponse &_param_17);

	/// Web service operation 'CreateItem' (returns error code or SOAP_OK)
	virtual	int CreateItem(ews1__CreateItemType *ews1__CreateItem, struct __ews1__CreateItemResponse &_param_18) { return this->CreateItem(NULL, NULL, ews1__CreateItem, _param_18); }
	virtual	int CreateItem(const char *endpoint, const char *soap_action, ews1__CreateItemType *ews1__CreateItem, struct __ews1__CreateItemResponse &_param_18);

	/// Web service operation 'DeleteItem' (returns error code or SOAP_OK)
	virtual	int DeleteItem(ews1__DeleteItemType *ews1__DeleteItem, struct __ews1__DeleteItemResponse &_param_19) { return this->DeleteItem(NULL, NULL, ews1__DeleteItem, _param_19); }
	virtual	int DeleteItem(const char *endpoint, const char *soap_action, ews1__DeleteItemType *ews1__DeleteItem, struct __ews1__DeleteItemResponse &_param_19);

	/// Web service operation 'UpdateItem' (returns error code or SOAP_OK)
	virtual	int UpdateItem(ews1__UpdateItemType *ews1__UpdateItem, struct __ews1__UpdateItemResponse &_param_20) { return this->UpdateItem(NULL, NULL, ews1__UpdateItem, _param_20); }
	virtual	int UpdateItem(const char *endpoint, const char *soap_action, ews1__UpdateItemType *ews1__UpdateItem, struct __ews1__UpdateItemResponse &_param_20);

	/// Web service operation 'SendItem' (returns error code or SOAP_OK)
	virtual	int SendItem(ews1__SendItemType *ews1__SendItem, struct __ews1__SendItemResponse &_param_21) { return this->SendItem(NULL, NULL, ews1__SendItem, _param_21); }
	virtual	int SendItem(const char *endpoint, const char *soap_action, ews1__SendItemType *ews1__SendItem, struct __ews1__SendItemResponse &_param_21);

	/// Web service operation 'MoveItem' (returns error code or SOAP_OK)
	virtual	int MoveItem(ews1__MoveItemType *ews1__MoveItem, struct __ews1__MoveItemResponse &_param_22) { return this->MoveItem(NULL, NULL, ews1__MoveItem, _param_22); }
	virtual	int MoveItem(const char *endpoint, const char *soap_action, ews1__MoveItemType *ews1__MoveItem, struct __ews1__MoveItemResponse &_param_22);

	/// Web service operation 'CopyItem' (returns error code or SOAP_OK)
	virtual	int CopyItem(ews1__CopyItemType *ews1__CopyItem, struct __ews1__CopyItemResponse &_param_23) { return this->CopyItem(NULL, NULL, ews1__CopyItem, _param_23); }
	virtual	int CopyItem(const char *endpoint, const char *soap_action, ews1__CopyItemType *ews1__CopyItem, struct __ews1__CopyItemResponse &_param_23);

	/// Web service operation 'CreateAttachment' (returns error code or SOAP_OK)
	virtual	int CreateAttachment(ews1__CreateAttachmentType *ews1__CreateAttachment, struct __ews1__CreateAttachmentResponse &_param_24) { return this->CreateAttachment(NULL, NULL, ews1__CreateAttachment, _param_24); }
	virtual	int CreateAttachment(const char *endpoint, const char *soap_action, ews1__CreateAttachmentType *ews1__CreateAttachment, struct __ews1__CreateAttachmentResponse &_param_24);

	/// Web service operation 'DeleteAttachment' (returns error code or SOAP_OK)
	virtual	int DeleteAttachment(ews1__DeleteAttachmentType *ews1__DeleteAttachment, struct __ews1__DeleteAttachmentResponse &_param_25) { return this->DeleteAttachment(NULL, NULL, ews1__DeleteAttachment, _param_25); }
	virtual	int DeleteAttachment(const char *endpoint, const char *soap_action, ews1__DeleteAttachmentType *ews1__DeleteAttachment, struct __ews1__DeleteAttachmentResponse &_param_25);

	/// Web service operation 'GetAttachment' (returns error code or SOAP_OK)
	virtual	int GetAttachment(ews1__GetAttachmentType *ews1__GetAttachment, struct __ews1__GetAttachmentResponse &_param_26) { return this->GetAttachment(NULL, NULL, ews1__GetAttachment, _param_26); }
	virtual	int GetAttachment(const char *endpoint, const char *soap_action, ews1__GetAttachmentType *ews1__GetAttachment, struct __ews1__GetAttachmentResponse &_param_26);

	/// Web service operation 'CreateManagedFolder' (returns error code or SOAP_OK)
	virtual	int CreateManagedFolder(ews1__CreateManagedFolderRequestType *ews1__CreateManagedFolder, struct __ews1__CreateManagedFolderResponse &_param_27) { return this->CreateManagedFolder(NULL, NULL, ews1__CreateManagedFolder, _param_27); }
	virtual	int CreateManagedFolder(const char *endpoint, const char *soap_action, ews1__CreateManagedFolderRequestType *ews1__CreateManagedFolder, struct __ews1__CreateManagedFolderResponse &_param_27);

	/// Web service operation 'GetDelegate' (returns error code or SOAP_OK)
	virtual	int GetDelegate(ews1__GetDelegateType *ews1__GetDelegate, struct __ews1__GetDelegateResponse &_param_28) { return this->GetDelegate(NULL, NULL, ews1__GetDelegate, _param_28); }
	virtual	int GetDelegate(const char *endpoint, const char *soap_action, ews1__GetDelegateType *ews1__GetDelegate, struct __ews1__GetDelegateResponse &_param_28);

	/// Web service operation 'AddDelegate' (returns error code or SOAP_OK)
	virtual	int AddDelegate(ews1__AddDelegateType *ews1__AddDelegate, struct __ews1__AddDelegateResponse &_param_29) { return this->AddDelegate(NULL, NULL, ews1__AddDelegate, _param_29); }
	virtual	int AddDelegate(const char *endpoint, const char *soap_action, ews1__AddDelegateType *ews1__AddDelegate, struct __ews1__AddDelegateResponse &_param_29);

	/// Web service operation 'RemoveDelegate' (returns error code or SOAP_OK)
	virtual	int RemoveDelegate(ews1__RemoveDelegateType *ews1__RemoveDelegate, struct __ews1__RemoveDelegateResponse &_param_30) { return this->RemoveDelegate(NULL, NULL, ews1__RemoveDelegate, _param_30); }
	virtual	int RemoveDelegate(const char *endpoint, const char *soap_action, ews1__RemoveDelegateType *ews1__RemoveDelegate, struct __ews1__RemoveDelegateResponse &_param_30);

	/// Web service operation 'UpdateDelegate' (returns error code or SOAP_OK)
	virtual	int UpdateDelegate(ews1__UpdateDelegateType *ews1__UpdateDelegate, struct __ews1__UpdateDelegateResponse &_param_31) { return this->UpdateDelegate(NULL, NULL, ews1__UpdateDelegate, _param_31); }
	virtual	int UpdateDelegate(const char *endpoint, const char *soap_action, ews1__UpdateDelegateType *ews1__UpdateDelegate, struct __ews1__UpdateDelegateResponse &_param_31);

	/// Web service operation 'GetUserAvailability' (returns error code or SOAP_OK)
	virtual	int GetUserAvailability(ews1__GetUserAvailabilityRequestType *ews1__GetUserAvailabilityRequest, struct __ews1__GetUserAvailabilityResponse &_param_32) { return this->GetUserAvailability(NULL, NULL, ews1__GetUserAvailabilityRequest, _param_32); }
	virtual	int GetUserAvailability(const char *endpoint, const char *soap_action, ews1__GetUserAvailabilityRequestType *ews1__GetUserAvailabilityRequest, struct __ews1__GetUserAvailabilityResponse &_param_32);

	/// Web service operation 'GetUserOofSettings' (returns error code or SOAP_OK)
	virtual	int GetUserOofSettings(ews1__GetUserOofSettingsRequest *ews1__GetUserOofSettingsRequest_, struct __ews1__GetUserOofSettingsResponse &_param_33) { return this->GetUserOofSettings(NULL, NULL, ews1__GetUserOofSettingsRequest_, _param_33); }
	virtual	int GetUserOofSettings(const char *endpoint, const char *soap_action, ews1__GetUserOofSettingsRequest *ews1__GetUserOofSettingsRequest_, struct __ews1__GetUserOofSettingsResponse &_param_33);

	/// Web service operation 'SetUserOofSettings' (returns error code or SOAP_OK)
	virtual	int SetUserOofSettings(ews1__SetUserOofSettingsRequest *ews1__SetUserOofSettingsRequest_, struct __ews1__SetUserOofSettingsResponse &_param_34) { return this->SetUserOofSettings(NULL, NULL, ews1__SetUserOofSettingsRequest_, _param_34); }
	virtual	int SetUserOofSettings(const char *endpoint, const char *soap_action, ews1__SetUserOofSettingsRequest *ews1__SetUserOofSettingsRequest_, struct __ews1__SetUserOofSettingsResponse &_param_34);
};
#endif
