/* -*- mode: IDL; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
#include "nsISupports.idl"

[scriptable, uuid(0eae86b6-5bff-11e5-850f-0023246c28f3)]
interface IContactEwsDirectory : nsISupports
{
    bool shouldUseForAutoComplete(in ACString idKey);
};
